version: '3'

services:
  docker-mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=url_shortener
      - MYSQL_PASSWORD=root
  spring-boot-jpa-docker-webapp:
    image: url-shortener-app
    depends_on:
      - docker-mysql
    ports:
      - 8181:8080
    environment:
      - DATABASE_HOST=docker-mysql
      - DATABASE_USER=root
      - DATABASE_PASSWORD=root
      - DATABASE_NAME=url_shortener
      - DATABASE_PORT=3306